services:
  mongo:
    image: mongo:7
    container_name: depanno-mongo
    ports:
      - "27017:27017"
    volumes:
      - depanno_mongo_data:/data/db
    restart: unless-stopped

volumes:
  depanno_mongo_data:
